### ISSUE TITLE
Correction to test name in ReadMe

### ISSUE THREAD

**Issue by Nirvikalpa108** [tes/scoreboard#1]
Hi @stecb 

I just want to check that the ReadMe is correct when it says [here](https://github.com/tes/scoreboard#requirements) that the first test is called `getGameScore`? 

From the `scoreboard.test.js` file line 12 I see the first test is called `initialState`. I'm sure the ReadMe is probably correct, but just wanted to double check in case.

Thank you so much ❤️

**Comment by stecb** [comment]
Hey @Nirvikalpa108 :) yep that first one on the readme is the first `failing` one :) the `initialState` one should be passing.

**Comment by Nirvikalpa108** [comment]
Perfect, I understand the ReadMe now. Thank you!
